persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_type all

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true
max_qos 2
max_inflight_messages 0
max_queued_messages 1000
queue_qos0_messages true
persist_client_subscription true
autosave_interval 60
